### ISSUE TITLE
Blacklisted folders

### ISSUE THREAD

**Issue by billmcct** [alphaonex86/Ultracopier#104]
How the hell do I stop ultra copier from blacklisting my folders?

**Comment by alphaonex86** [comment]
I disable some folder for a reason, if you copy from or to, windows use real path and not virtual path.
Mean I will fill your disk by data that's never be acceded or delete, as ghost folder just using space.
And of course ultracopier will show have copied the data, but when you open the folder it remain empty.

**Comment by billmcct** [comment]
OK, but it blacklists folders on my external drives which are all absolute paths.

**Comment by alphaonex86** [comment]
This week I will release a new version with option to disable blacklist folder, to use with care

**Comment by billmcct** [comment]
Thank you very much.

**Comment by alphaonex86** [comment]
Done

**Comment by e-t-l** [comment]
> I disable some folder for a reason, if you copy from or to, windows use real path and not virtual path. Mean I will fill your disk by data that's never be acceded or delete, as ghost folder just using space. And of course ultracopier will show have copied the data, but when you open the folder it remain empty.

I don't fully understand this. Is there a way to detect and cleanup these "ghost folders"?

Note: I run Ultracopier as Admin, and it successfully copies to blacklisted folders. Ultracopier shows a blacklist error, but the files do actually get copied regardless.

**Comment by alphaonex86** [comment]
I never found way to cleanup the ghost folder, except formating the whole disk.
Ultracopier as Admin generate problem in some case. With the new option should block the folder in blacklist or just allow it without error.
Can you say me if the checkbox is checked?

**Comment by e-t-l** [comment]
> I never found way to cleanup the ghost folder, except formating the whole disk.

Wow, that's not good 😬

> Ultracopier as Admin generate problem in some case. With the new option should block the folder in blacklist or just allow it without error.
> Can you say me if the checkbox is checked?

To be clear, I was running Ultracopier as Admin BEFORE updating to v2.2.7.0, so there was no checkbox to ignore blacklist. 

When I did that, I did occasionally copy files to blacklisted folders. And like I described, Ultracopier gave the "blacklisted folder" error, but the file copy succeeded anyway. Is there any way for me to find out whether it was creating shadow folders when I did this? Is there a way to view these shadow folders if they exist?

**Comment by alphaonex86** [comment]
I never be able to access/view to this folder. This is very specific to Windows and I don't have idea how improve this

**Comment by e-t-l** [comment]
Ok. I'm just trying to understand the problem. I am asking how you *detect* whether a ghost folder exists?

**Comment by alphaonex86** [comment]
It's when:

- You copy to destination and file manager (explorer.exe on Windows) don't show the new file copied when Ultracopier say all is ok
- You copy from source and Ultracopier not found files/folder where you see into file manager (explorer.exe on Windows) the path contain what do you try copy
- EVEN WORSE: you *move* folder to blacklisted folder, the source the delete and file manager (explorer.exe on Windows) don't show it
- in case of copy even if you not see the file/folder, the used space disk have grow
- in case of move even if you not see the file/folder, the used space disk have not change

The unique way this ghost folder is user another OS like Linux
