### ISSUE TITLE
[Mac] Tray icon disappears on first window open

### ISSUE THREAD

**Issue by pandaiolo** [alphaonex86/Ultracopier#11]
I am using Ultracopier for mac, and everytime I use it, there is this same issue :
1. Open Ultracopier from the `Applications` folder
2. As expected: the tray icon appears
3. Click on the tray icon to open Ultracopier, for whatever reason (make a copy, see the version, anything)
4. Unexpected : the tray icon disappears

Even after open Ultracopier window is closed, tray icon does not come back. When I click on the Ultracopier in the Dock, I can see the Ultracopier menu in the menubar, and Quit. Relaunching the full thing from `Applications` folder is the only way I found to get the icon back.

OS Version : OSX El Capitan, but I think it was the same on Yosemite

**Comment by alphaonex86** [comment]
I don't have Mac to test that'd from now.

**Comment by pandaiolo** [comment]
I did some research : it appears it's a Qt bug : https://bugreports.qt.io/browse/QTBUG-42910

It seems from that discussion that updating Qt to version `>=5.4.2` fixes this issue. If you're able to bump the version of Qt next release, that would be awesome ! Thanks !

**Comment by alphaonex86** [comment]
Not for the near futur, but I need update my compilation chain for CatchChallenger 2, then I will update for Ultracopier too.

**Comment by alphaonex86** [comment]
Done
