### ISSUE TITLE
[Feature Request] Set a timeout for file access issues

### ISSUE THREAD

**Issue by pandaiolo** [alphaonex86/Ultracopier#12]
Is there any way to set a timeout on file access ? I just had a copy stall for many hours on a single file because it could not be read. 
- If it's already a feature : how to activate it ?
- If it's already an activated feature : there's a bug :-)
- If it's not a feature: that would be a nice addition

BTW Thank you for this awesome tool, can't wait for a good will to develop copycatch for mac !

**Comment by alphaonex86** [comment]
Not possible with version 1 due to sync API.
The version 2 will use async not blocking API and will allow that's.

**Comment by pandaiolo** [comment]
:+1:

**Comment by alphaonex86** [comment]
Not possible with posix/windows API
