### ISSUE TITLE
[Mac] Remaining time inaccurate when paused

### ISSUE THREAD

**Issue by pandaiolo** [alphaonex86/Ultracopier#13]
It seems that remaining time is computed by taking the whole time since the copy started, which is OK if the copy was not interrupted, but leads to serious inaccuracy when copy has been paused.

Pause time should be excluded from remaining time computation

I am opening this issue because I saw the remaining time stating hundreds of hours after resuming. The remaining time becomes realistic again after some time, but not immediately.

Also, there is a lot of variability in the remaining time, even after a while copying, like if the current speed was only accounted for, not an average.

**Comment by alphaonex86** [comment]
It's due to OS ressource managements, reset of internal variables, ... if you have better way to do you can propose a patch.

**Comment by pandaiolo** [comment]
Sure, although I don't have the time currently (but I do propose PRs when I do :) ). No issue was open about this, so I just wanted to report it. Hope it helps. Cheers.

**Comment by alphaonex86** [comment]
On the forum it was discuted.
