### ISSUE TITLE
linux binary

### ISSUE THREAD

**Issue by revast** [alphaonex86/Ultracopier#14]
hi,
here are my writings on how to compile on linux:

http://pastebin.com/g4auygus

Could be simpler.. I guess. Would be nice to have a script for that.

I would also like if you could provide a compiled, selfcontainend linux version. No need to package it up for different distros. I pointed out how I did it , I hope you will comment to the process and the errors I got and the questions that bumped up, and get inspired to make at least simple binary release for linux as well.

I made a debian package with qt54 libs bundled up inside, so It even runs on platforms where qt54 is not available, e.g ubuntu 14.04:

http://openartisthq.org/debian/trusty64/ultracopier_1.2.1.1-1~openArtist1_amd64.deb

**Comment by lestcape** [comment]
+1

**Comment by alphaonex86** [comment]
+1 I have never succes this packaging, always failed on some distro.
Have you tar to test on my distro?
But my main objective is intergration into the distro.

**Comment by lestcape** [comment]
@alphaonex86 i think if you change your project structure to automatically package your software for debian here in github, other distros can also consume your structure and then recreate packages for other linux distros as well in an easy way.

**Comment by alphaonex86** [comment]
I was do it, was very more hard to maintain and no body have do that's.
I will do better an .pro to just compil and run.

**Comment by revast** [comment]
a .deb file is also not more than an archive. You can just extract its content with e.g. file-roller. You can use my .deb as blueprint for building a simple debian package, everything is right in place. (some hints are here: http://pastebin.com/UZErQaU5 ). Or just zip the /opt/ultrcopier folder and the /usr/bin/ultracopier shell script for a binary release.

Complying to debian's  Lintian mechanism (for having the package officially in debian/ubuntu) 
is a whole other story. 
As ultracopier already IS in debian/ubuntu (version 0.3 though), one could use this old version as a starting point:
apt-get source ultracopier 
Making an ubuntu ppa out of that is rather easy, not very ditribution-agnositc, but nice to have.

You could also try to contact the original maintainer of the original debian package, Thomas Preud'homme robotux@debain.org and ask if he would help out.

Here I pointed out that there are plenty of other possible ways of distribution:
https://github.com/mkeeter/antimony/issues/52#issuecomment-111980255
Opensuse build server is definitely great, If you find out how to set that up. I would ask florian Hoech about that, as he does exceptionally well in distributing his dispcalgui software. Besides Opensuse build server, he also uses zeroInstall for example.

> I will do better an .pro to just compil and run. 
That would be nice to have, and would attract many package maintainers from other distros I guess. 

Sticking together a little script which auto-compiles a binary with all its dependencies (two versions for 32 and 64bit), self-contained in one folder, which then is tar.gz'd should also be rather easy.

**Comment by alphaonex86** [comment]
Opensuse build server -> should be the best solution.

**Comment by lestcape** [comment]
Thats was fast @alphaonex86. @revast you sure are right in all that you say. I hope some one in debian considered add the packages, because if it's in debian is in ubuntu and mint. Also the Arch users sure will be happy to  easy compile it...

**Comment by alphaonex86** [comment]
It's not finished, the principe it's done, it compil but not work, I will continue to work on this to do the new version fully functionnal.
I was lot of in contact with Preud'homme, but now don't have time. Before the problem was Qt5, after Qt5Sysinfo, now nothing.

**Comment by alphaonex86** [comment]
ultracopier-all-in-one-direct.pro work now for me, I have extensivly reused the work of CatchChallenger for this packaging, seam work correctly. Anybody can confirm?

**Comment by RyDroid** [comment]
```
$ qmake ultracopier-all-in-one-direct.pro 
RCC: Error in 'resources/ultracopier-resources.qrc': Cannot find file 'Languages/en/translation.qm'
RCC: Error in 'plugins/static-plugins.qrc': Cannot find file 'CopyEngine/Ultracopier/Languages/fr/translation.qm'
RCC: Error in 'plugins/static-plugins.qrc': Cannot find file 'Languages/fr/translation.qm'
RCC: Error in 'plugins/static-plugins.qrc': Cannot find file 'Themes/Oxygen/Languages/fr/translation.qm'
```

**Comment by alphaonex86** [comment]
You need compil as all Qt software the .ts into .qm via qt linguist

**Comment by Pival81** [comment]
So, is there a way to compile this on linux? what are the requirements?

**Comment by alphaonex86** [comment]
You need compile the .qrc, all the rest is into the README, test from comit https://github.com/alphaonex86/Ultracopier/commit/2923dbd62f7dd9c81da8e8b775b3471e66394e66

**Comment by RyDroid** [comment]
```
$ qmake ultracopier-all-in-one-direct.pro
RCC: Error in 'resources/ultracopier-resources.qrc': Cannot find file 'Languages/en/translation.qm'
RCC: Error in 'plugins/static-plugins.qrc': Cannot find file 'CopyEngine/Ultracopier/Languages/fr/translation.qm'
RCC: Error in 'plugins/static-plugins.qrc': Cannot find file 'Languages/fr/translation.qm'
RCC: Error in 'plugins/static-plugins.qrc': Cannot find file 'Themes/Oxygen/Languages/fr/translation.qm'
$ lrelease ultracopier-all-in-one-direct.pro
$ qmake ultracopier-all-in-one-direct.pro
RCC: Error in 'plugins/static-plugins.qrc': Cannot find file 'CopyEngine/Ultracopier/Languages/fr/translation.qm'
RCC: Error in 'plugins/static-plugins.qrc': Cannot find file 'Themes/Oxygen/Languages/fr/translation.qm'
$ rcc plugins/static-plugins.qrc
RCC: Error in 'plugins/static-plugins.qrc': Cannot find file 'CopyEngine/Ultracopier/Languages/fr/translation.qm'
```

http://ultracopier-wiki.first-world.info/wiki/Installation_from_sources does not help.

**Comment by alphaonex86** [comment]
Just craete empty .qm at tyhe mentioned place. Or get this file from windows version on the website.

**Comment by RyDroid** [comment]
```
$ mkdir -p CopyEngine/Ultracopier/Languages/fr/
$ touch CopyEngine/Ultracopier/Languages/fr/translation.qm
$ mkdir -p Themes/Oxygen/Languages/fr/
$ touch Themes/Oxygen/Languages/fr/translation.qm
$ ls -l CopyEngine/Ultracopier/Languages/fr/translation.qm Themes/Oxygen/Languages/fr/translation.qm
-rw-rw-r-- 1 user user 0 juil. 14 19:25 CopyEngine/Ultracopier/Languages/fr/translation.qm
-rw-rw-r-- 1 user user 0 juil. 14 19:25 Themes/Oxygen/Languages/fr/translation.qm
$ qmake ultracopier-all-in-one-direct.pro
RCC: Error in 'plugins/static-plugins.qrc': Cannot find file 'CopyEngine/Ultracopier/Languages/fr/translation.qm'
RCC: Error in 'plugins/static-plugins.qrc': Cannot find file 'Themes/Oxygen/Languages/fr/translation.qm'
```

I would like to build from source without blobs that can not be rebuilt.

**Comment by alphaonex86** [comment]
```
$ cd plugins/
$ mkdir -p CopyEngine/Ultracopier/Languages/fr/
$ touch CopyEngine/Ultracopier/Languages/fr/translation.qm
$ mkdir -p Themes/Oxygen/Languages/fr/
$ touch Themes/Oxygen/Languages/fr/translation.qm
```

**Comment by RyDroid** [comment]
Thanks.

```
$ qmake ultracopier-all-in-one-direct.pro
user@user-ThinkPad-X200:~/workspace/Ultracopier$ make
/usr/lib/x86_64-linux-gnu/qt5/bin/uic HelpDialog.ui -o ui_HelpDialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic PluginInformation.ui -o ui_PluginInformation.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic OptionDialog.ui -o ui_OptionDialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic OSSpecific.ui -o ui_OSSpecific.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic plugins/CopyEngine/Ultracopier/copyEngineOptions.ui -o ui_copyEngineOptions.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic plugins/CopyEngine/Ultracopier/debugDialog.ui -o ui_debugDialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic plugins/CopyEngine/Ultracopier/DiskSpace.ui -o ui_DiskSpace.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic plugins/CopyEngine/Ultracopier/fileErrorDialog.ui -o ui_fileErrorDialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic plugins/CopyEngine/Ultracopier/fileExistsDialog.ui -o ui_fileExistsDialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic plugins/CopyEngine/Ultracopier/fileIsSameDialog.ui -o ui_fileIsSameDialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic plugins/CopyEngine/Ultracopier/FilterRules.ui -o ui_FilterRules.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic plugins/CopyEngine/Ultracopier/Filters.ui -o ui_Filters.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic plugins/CopyEngine/Ultracopier/folderExistsDialog.ui -o ui_folderExistsDialog.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic plugins/CopyEngine/Ultracopier/RenamingRules.ui -o ui_RenamingRules.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic plugins/Themes/Oxygen/themesOptions.ui -o ui_themesOptions.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic plugins/Themes/Oxygen/options.ui -o ui_options.h
/usr/lib/x86_64-linux-gnu/qt5/bin/uic plugins/Themes/Oxygen/interface.ui -o ui_interface.h
g++ -c -m64 -pipe -std=c++0x -Wall -Wextra -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIE -DULTRACOPIER_PLUGIN_ALL_IN_ONE -DULTRACOPIER_PLUGIN_ALL_IN_ONE -DULTRACOPIER_PLUGIN_ALL_IN_ONE_DIRECT -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I. -o ThemesManager.o ThemesManager.cpp
In file included from ThemesManager.h:18:0,
                 from ThemesManager.cpp:10:
ResourcesManager.h:38:15: error: ‘__cxx11’ in namespace ‘std’ does not name a type
         const std::__cxx11::string &getWritablePath() const;
               ^
make: *** [ThemesManager.o] Erreur 1
```

I am running on Trisquel GNU/Linux 7, based on Ubuntu 14.04 LTS. So my version of g++ is 4.8. Is it needed to use the new implementation of string? https://stackoverflow.com/questions/37004976/undefined-reference-to-processstd-cxx11basic-string-when-compiling-a

**Comment by alphaonex86** [comment]
As writen above: test from comit 2923dbd

**Comment by darkdragon-001** [comment]
I would like to ask for clarification on @revast's questions:

What is the `plugins-alternative` folder for?

**Comment by alphaonex86** [comment]
For all the plugin unmaintened, poor tested or poor coded

**Comment by darkdragon-001** [comment]
Can you please include `cpp11additionstringtointcpp.cpp`.

**Comment by alphaonex86** [comment]
Done, sorry

**Comment by darkdragon-001** [comment]
I get the following error:

```
(     965) ResourcesManager.cpp:86:ResourcesManager(), (location: Core): searchPath.at(0): :/
(     965) ResourcesManager.cpp:89:ResourcesManager(), (location: Core): writablePath: /home/mschnirring/Development/ultracopier/Ultracopier/
(     966) OptionEngine.cpp:82:addOptionGroup(), (location: Core): start("Ultracopier",[...])
(     966) OptionEngine.cpp:117:addOptionGroup(), (location: Core): The current key: Ultracopier, group: Last_version_used, have value: 1.2.3.6
(     966) OptionEngine.cpp:117:addOptionGroup(), (location: Core): The current key: Ultracopier, group: displayOSSpecific, have value: false
(     966) OptionEngine.cpp:82:addOptionGroup(), (location: Core): start("CopyEngine",[...])
(     966) OptionEngine.cpp:82:addOptionGroup(), (location: Core): start("Write_log",[...])
(     967) OptionEngine.cpp:82:addOptionGroup(), (location: Core): start("CopyListener",[...])
(     967) OptionEngine.cpp:82:addOptionGroup(), (location: Core): start("SessionLoader",[...])
(     967) PluginsManager.cpp:19:PluginsManager(), (location: Core): start
(     967) LanguagesManager.cpp:16:LanguagesManager(), (location: Core): start
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
```

This is because `pluginsListIndexed` is empty. This is because `PluginsManager` has not finished loading (`pluginLoaded == false`).

I guess `LanguagesManager` thread should only be started after plugins is  loaded. Nevertheless, all getter functions (especially `getPluginsByCategory()`) should check if loading is finished before returning a value. Otherwise return an exception.

**Comment by alphaonex86** [comment]
I will check theses days the running error, this git version is 1.4 and 95% code rewrite.

**Comment by darkdragon-001** [comment]
I started writing a [linux script](https://github.com/darkdragon-001/Ultracopier/blob/further_c%2B%2B11/tools/to-pack/3-compil-linux.sh). Feel free to modify on that basis.

Unfortunately, only the _debug_ version with the single project works. Other plugins are not yet migrated to c++11 or have other problems...

**Comment by alphaonex86** [comment]
https://pastebin.com/VQUVEsLs for windows, I need 2 debug mode, the gcc -g debug (for crash mostly) and debug (macro for log, to debug without crash), I have to switch from winehq to mxe for the windows binary.

For linux, compiling only ultracopier.pro is correct, it's all in one version, with the correct linux plugin.
./other-pro/ultracopier-core.pro it's for modular version (Windows and mac)

I will look to progress on the other plugins this week

**Comment by alphaonex86** [comment]
PluginLoader/catchcopy-v0002/ -> it's for Windows only

**Comment by darkdragon-001** [comment]
I started to [fix](https://github.com/darkdragon-001/Ultracopier/tree/fix_projects) the individual projects (Qt Creator). I didn't succeed with the core. When running the linked code, it compiles but throws runtime errors:

```
QObject::connect: Cannot queue arguments of type 'std::vector<std::string>'
(Make sure 'std::vector<std::string>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'std::string'
(Make sure 'std::string' is registered using qRegisterMetaType().)
```

**Comment by alphaonex86** [comment]
Hi, should be fixed now

**Comment by darkdragon-001** [comment]
One question for packaging:
Which resource files need to be included?

**Comment by alphaonex86** [comment]
None for ./ultracopier.pro

**Comment by darkdragon-001** [comment]
So language files and image resources are automatically included in the binary file?
(because they are mentioned in the corresponding resources files)

**Comment by alphaonex86** [comment]
correct

**Comment by darkdragon-001** [comment]
Are themes supposed to be working at the moment?

**Comment by alphaonex86** [comment]
yes, but plugin and modular part disabled for ultracopier.pro it will be only enable for core version

**Comment by darkdragon-001** [comment]
I am using [this script](https://github.com/darkdragon-001/Ultracopier/blob/linux/tools/to-pack/3-compil-linux.sh) to build the core version (parameter: `DEBUG=0`), but it does not work for me...

**Comment by alphaonex86** [comment]
./3.sh: line 32: [: -eq: unary operator expected
./3.sh: line 37: [: -eq: unary operator expected
./3.sh: line 40: [: -eq: unary operator expected

I have put in same place where is in git

**Comment by darkdragon-001** [comment]
Run via `./tools/to-pack/3-compile-linux.sh "./build" 0 1 1` from project root.

**Comment by alphaonex86** [comment]
build_plugin -> should return $? and exit if $? != 0

build_plugin "${args}" "${TARGET}" "./plugins/PluginLoader/catchcopy-v0002/pluginLoader.pro" -> is for windows only
build_plugin "${args}" "${TARGET}" "./plugins/CopyEngine/Rsync/Rsync.pro" -> do as separate for risk of data destruction (as rsync)
For now this script seam unclear about what's part is the problem because it continue to compile

**Comment by darkdragon-001** [comment]
The script is work in progress. But it compiles successfully for me. It also runs (`./build/package/ultracopier`), but when I open _Options > Themes_, I can't change it...

**Comment by darkdragon-001** [comment]
It seems that the themes error message is gone after fixing the other errors. Although, I don't see a big difference between _Oxygen_ and _Supercopier_...

**Comment by alphaonex86** [comment]
This version 1.4 is 95% remaked from Qt to C++17... then it should very more buggy.
Yes, Supercopier is more for nostalgic of SuperCopier (old brand) under Windows 98. Actually the old name remain at 70% for Supercopier, against 30% for Ultracopier.

**Comment by alphaonex86** [comment]
And this it's without speak of the version 2, std::filesystem, drop this **** of Qt sync API + 250 thread just because QFile need to be open, read/write, close into the same thread.

**Comment by darkdragon-001** [comment]
What is the (empty) `plugin.json` used for?

**Comment by alphaonex86** [comment]
A requirement for Qt plugins system...

**Comment by revast** [comment]
I tried the script for compiling now, works until : 

```
<command-line>:0:0: note: this is the location of the previous definition
mv: 'libinterface.so' and './libinterface.so' are the same file
make: [libinterface.so] Error 1 (ignored)
```

btw, the the correct dependencies for ubuntu are:

`sudo apt-get install  qt5-qmake qttools5-dev-tools  qtbase5-dev-tools  qtbase5-dev`

**Comment by alphaonex86** [comment]
This script is outdated, generate the .qm from the .ts
https://pastebin.com/As64Ng20

And after just compile the ultracopier.pro via qmake;make

**Comment by revast** [comment]
ok, I tried that, but then I get

```
qmake ultracopier.pro 
Info: creating stash file /media/vault/compiles/ultracopier/Ultracopier-master/.qmake.stash
RCC: Error in 'resources/ultracopier-resources.qrc': Cannot find file 'Languages/en/translation.qm'
RCC: Error in 'plugins/static-plugins.qrc': Cannot find file 'CopyEngine/Ultracopier/Languages/fr/translation.qm'
RCC: Error in 'plugins/static-plugins.qrc': Cannot find file 'Languages/fr/translation.qm'
RCC: Error in 'plugins/static-plugins.qrc': Cannot find file 'Themes/Oxygen/Languages/fr/translation.qm'
```

**Comment by alphaonex86** [comment]
create this .qm file, with empty file, text file but with this name

**Comment by darkdragon-001** [comment]
In case anybody is interested: [My script](https://github.com/darkdragon-001/Ultracopier/blob/linux/tools/to-pack/3-compil-linux.sh) works for some while now.

DEBUG=1 uses the all-in-one `ultracopier.pro` and puts the result in `./build`
DEBUG=0 builds the different components (core, plugins) separately and puts the result in the `./package` folder.
