### ISSUE TITLE
Does not seem to replace default explorer copy system

### ISSUE THREAD

**Issue by intika** [alphaonex86/Ultracopier#15]
i am under windows 10 
on "regsvr32.exe catchcopy32.dll"
the command say succeeded. 

automatic copy still does not work... explorer still make the copy... 
any advice ? 

thanks

**Comment by intika** [comment]
catchcopy32 from supercopier v4.0.1.13
works but the last version v1.2... does not

**Comment by alphaonex86** [comment]
Hello,

1) 2 version of catchcopy32 can't be loaded
2) to fully unload you need regsvr32.exe /u catchcopy32.dll and reboot
3) you have windows 10 32Bits?
4) The debug version of this dll: http://files.first-world.info/ultracopier/1.2.3.5/ultracopier-debug-windows-x86-1.2.3.5.zip is very more verbose and will spam you of messagebox to give you mor details.
5) The change is only to not trigger the UAC

Cheers,

**Comment by intika** [comment]
1. Yes i guess so... (i started looking after it because it does not work after rebooting while testing the last release) 
2. yep i know and i did
3. Win 10 32Bits Build 10240 - UAC Fully disabled
4. i downloaded it to have a look... i am also compiling from source i would like to add a feature to the theme interface to play a sound on "copy error" and "finish copy" like teracopy do... i will pull request ;)
5. may be it's caused by my disabled UAC

Thanks for the answer ;)

**Comment by alphaonex86** [comment]
The code is very very simple for intercept the copy:
https://github.com/alphaonex86/Catchcopy
4) take care if the code is win32, you need a clear code to be included, revised and maintened (I'm not a win32 dev) or you can do in multiplatform
5) maybe, on freshly installed win10 64Bits all work as excepted.
6) The debug version give to a log to debug the return code of regsvr32 and their console output, it can be interesting to see it in case of failure

**Comment by intika** [comment]
Thanks bro :)

**Comment by intika** [comment]
Just finished my new feature :D i made a pull request... 
aaah i can now fully switch to ultracopy :+1: 
now i will have a look on catchcopy and let you know ;)

**Comment by alphaonex86** [comment]
For your note: I had thinks to that's but I prefer do in priority into Ultracopier: lock remover inclusion, the new copy engine based on event.
