### ISSUE TITLE
error compiling dbus.... 

### ISSUE THREAD

**Issue by revast** [alphaonex86/Ultracopier#21]
qt 5.6.1, ubuntu 16.04, comit 2923dbd

g++ -c -m64 -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o moc_listener.o moc_listener.cpp
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/QtCore:87:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtDBus/QtDBusDepends:3,
                 from /usr/include/x86_64-linux-gnu/qt5/QtDBus/QtDBus:3,
                 from listener.h:10,
                 from moc_listener.cpp:9:
moc_listener.cpp: In function ‘QObject* qt_plugin_instance()’:
moc_listener.cpp:203:22: error: invalid new-expression of abstract class type ‘Listener’
 QT_MOC_EXPORT_PLUGIN(Listener, Listener)
                      ^
In file included from moc_listener.cpp:9:0:
listener.h:18:7: note:   because the following virtual functions are pure within ‘Listener’:
 class Listener : public PluginInterface_Listener
       ^
In file included from listener.h:15:0,
                 from moc_listener.cpp:9:
../../../interface/PluginInterface_Listener.h:34:29: note: 	virtual QStringList PluginInterface_Listener::clientsList() const
         virtual QStringList clientsList() const = 0;
                             ^
Makefile:513: recipe for target 'moc_listener.o' failed
make: *** [moc_listener.o] Error 1

**Comment by alphaonex86** [comment]
dbug is outdate and not maintened plugins
