### ISSUE TITLE
Cant read modification dates at non-English paths

### ISSUE THREAD

**Issue by moceap** [alphaonex86/Ultracopier#22]
Continue from https://github.com/alphaonex86/Ultracopier/issues/20

**Comment by alphaonex86** [comment]
I had see this bug before, I can't see and access to some file via Qt. Any bug fix possible, the unique way is rewrite all the file manipulation without Qt (in progress).

**Comment by lestcape** [comment]
@alphaonex86 is strange to me that Qt will not have a way to load files parsing it to an specific encode. Qt need to have a way to do that... Just is a thing to find it... Rewrite all is a crazy idea...

**Comment by moceap** [comment]
@alphaonex86  May you use shell commands:

`stat -c %y $filename`

  I'm waiting.

**Comment by alphaonex86** [comment]
Not according:
1. Need the command exists and at the excepted place
2. Do context switching
3. Add lot of complexity

**Comment by moceap** [comment]
I tried to build after your last commit, but does not continue:

`g++ -c -pipe -std=c++0x -Wall -Wextra -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DULTRACOPIER_PLUGIN_ALL_IN_ONE -DULTRACOPIER_PLUGIN_ALL_IN_ONE -DULTRACOPIER_PLUGIN_ALL_IN_ONE_DIRECT -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o TransferThread.o plugins/CopyEngine/Ultracopier/TransferThread.cpp
In file included from /usr/include/qt5/QtCore/qnamespace.h:43:0,
                 from /usr/include/qt5/QtCore/qobjectdefs.h:48,
                 from /usr/include/qt5/QtCore/qobject.h:46,
                 from /usr/include/qt5/QtCore/qthread.h:43,
                 from /usr/include/qt5/QtCore/QThread:1,
                 from plugins/CopyEngine/Ultracopier/TransferThread.h:9,
                 from plugins/CopyEngine/Ultracopier/TransferThread.cpp:4:
/usr/include/qt5/QtCore/qobject.h: In instantiation of ‘static QMetaObject::Connection QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const typename QtPrivate::FunctionPointer<Func2>::Object*, Func2, Qt::ConnectionType) [with Func1 = void (WriteThread::*)(const Ultracopier::DebugLevel&, const QString&, const QString&, const QString&, const int&) const; Func2 = void (TransferThread::*)(const Ultracopier::DebugLevel&, std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char>, int) const; typename QtPrivate::FunctionPointer<Func>::Object = WriteThread; typename QtPrivate::FunctionPointer<Func2>::Object = TransferThread]’:
plugins/CopyEngine/Ultracopier/TransferThread.cpp:99:145:   required from here
/usr/include/qt5/QtCore/qobject.h:232:9: error: static assertion failed: Signal and slot arguments are not compatible.
         Q_STATIC_ASSERT_X((QtPrivate::CheckCompatibleArguments<typename SignalType::Arguments, typename SlotType::Arguments>::value),
         ^
make: *** [Makefile:2689: TransferThread.o] Error 1
`

**Comment by alphaonex86** [comment]
Hi, the master branch because I do directly the conversion to C++, I thinks I need 6 months more to finish it.

**Comment by moceap** [comment]
6 months!!  :(

**Comment by alphaonex86** [comment]
Is fixed with version 2?
