### ISSUE TITLE
Cleanup code

### ISSUE THREAD

**Issue by darkdragon-001** [alphaonex86/Ultracopier#24]
I am currently trying to compile it for linux (with help of #14). 
Getting rid of all those unused code parts (CGMINER #23, SUPERCOPIER, ...) would make contributing a lot easier ;)
Or does the supercopier part has any advantages aside from the name and icons?

**Comment by alphaonex86** [comment]
Done into the lasts commit. No advantage. Supercopier it's just a skin

**Comment by alphaonex86** [comment]
I have finish the base remake, now the last commit https://github.com/alphaonex86/Ultracopier/commit/f278540859bd9b2f75a18287d4ce0750f8f387e9 compile under my Linux

**Comment by darkdragon-001** [comment]
And what is the relation to TeraCopy?

**Comment by alphaonex86** [comment]
I had try do a TeraCopy skin to do easy transition for the user.

**Comment by alphaonex86** [comment]
Just a skin
