### ISSUE TITLE
Moving files results in destroyed Permissions under Linux.

### ISSUE THREAD

**Issue by revast** [alphaonex86/Ultracopier#28]
I use ultracopier  from commandline:
 (1.4.0.5 fresh from master, but this also happen with the 1.2.3.6 version)

` ultracopier mv ~/Downloads/luckybackup_0.4.9-1_amd64.deb ~/Videos`

what should happen:

file gets moved to ~/Videos 

permissions via ls -al:
`-rw-rw-r--  1 hero hero 4.8M Mar 15 11:26 luckybackup_0.4.9-1_amd64.deb`

via filebrowser:

![screenshot_2018-03-17_10-18-10](https://user-images.githubusercontent.com/8189198/37553652-91d0f176-29cc-11e8-890b-7fbe0c764a70.png)

what happens:

file gets moved to ~/Videos 

permissions via ls -al:

`----------  1 hero hero 4.8M Mar 15 11:26 luckybackup_0.4.9-1_amd64.deb`

via filebrowser:

![screenshot_2018-03-17_10-17-14](https://user-images.githubusercontent.com/8189198/37553644-6a0c70ac-29cc-11e8-8f47-0580f0d1b83c.png)

**Comment by alphaonex86** [comment]
Hi,
Can you test if http://doc.qt.io/qt-5/qfile.html#setPermissions-1 + http://doc.qt.io/qt-5/qfile.html#permissions work on your system? I just call this functions.
Cheers,

**Comment by alphaonex86** [comment]
Try a newer version of Qt else this will be fixed with the new standard C++17, the support will be done into the next years at compiler part.

**Comment by revast** [comment]
ok, I have tried with qt 5.9.4, and its the same problem.

I do not think it's the compiler's fault? There must be a way to fix this

**Comment by alphaonex86** [comment]
No, I don't think.
Test this code: https://pastebin.com/9Kvk1vmN need have into the current path: the file "source" and the file "destination"
Send me the output console or debug report to see if contains "Unable to get the source file permission" and "Unable to set the destination file permission"
See if it's on all file into all path, or just into specific case.

**Comment by revast** [comment]
hmm. I tried to compile with:

put file called  test.c in build folder
qmake -project
qmake 
make



but no luck so far:

https://pastebin.com/wTJmucyY

do you have a hint? or should I try with qtbuilder?

**Comment by alphaonex86** [comment]
With qt creator, new project, console application, replace the .c file content by the paste bin, compile, run, look into application output

**Comment by revast** [comment]
ok I have managed to do so, output with qt  5.9.4 is

` error`

**Comment by revast** [comment]
I guess that it works like it should then. 
Does that now mean the problem is not related to qt itself?

**Comment by alphaonex86** [comment]
and the destination permission is well set as source permission?

**Comment by revast** [comment]
yes. I tried different combinations of permissions.. It worked as is should...

**Comment by alphaonex86** [comment]
ok, then this same file, try with ultracopier in debug mode, send me the debug repport

**Comment by revast** [comment]
ok, I hope I did it right. https://pastebin.com/bh8udZtm

**Comment by alphaonex86** [comment]
Yes, you have do right, contact me into few day if I forgot

**Comment by alphaonex86** [comment]
Hi, can you try the new version into git?

**Comment by revast** [comment]
Yes! I can confirm that it is fixed now.

**Comment by alphaonex86** [comment]
Then I will publish the version 1.4.0.6 into this days, thanks for your repport, contact me in private to have a ultimate version key

**Comment by alphaonex86** [comment]
I have pushed a new version, it work too?

**Comment by revast** [comment]
yes, can confirm. I just recompiled and it works as it should.

**Comment by alphaonex86** [comment]
ok, 1.4.0.6 release, include this fix

**Comment by revast** [comment]
cool!
