### ISSUE TITLE
7-Zip and Ultracopier

### ISSUE THREAD

**Issue by topkekv2** [alphaonex86/Ultracopier#33]
There's a bug when extracting files using 7-zip : the temporary folder 7-zip is using isn't found by UltraCopier or deleted before actually copying files resulting in a "file not found" error in UltraCopier

**Comment by alphaonex86** [comment]
Should be fixed in version 2

**Comment by gerroon** [comment]
Hi

7zip issue seems to be still there at leastI think it is the same issue. Does this require some special setting to get it working?

**Comment by alphaonex86** [comment]
Hi, for now I don't have solution if not work. Windows file explorer don't support it, I don't see how do a work around.

**Comment by gerroon** [comment]
Thanks for the follow up. It makes sense

**Comment by gerroon** [comment]
Is it possible to ignore 7zip in this case? So if the files are coming from 7zip, UC just ignores and the explorer does copying instead?

**Comment by alphaonex86** [comment]
Hi, I had thinks to that's too. Windows API don't allow me it.

**Comment by gerroon** [comment]
Thanks, that is understandable I guess.
