### ISSUE TITLE
[UC] Folder with German letters Ä, ä, Ö, ö, Ü, ü, ß are not copied

### ISSUE THREAD

**Issue by WusWus** [alphaonex86/Ultracopier#34]
Hello, 

here is a bug report for Ultracopier v2. 0. 3. 4. 
Folders with the German letters Ä, ä, Ö, ö, Ü, ü, ß are not copied. The error message "No such file or directory" appears. 
Files with the letters are copied correctly.

Greetings 
WusWus

**Comment by alphaonex86** [comment]
Hi,
What is the sources and destination?
Here with this letter and windows 7 64Bits NTFS all working.
Cheers,

**Comment by WusWus** [comment]
![Problem_with_GermanLetters](https://user-images.githubusercontent.com/51401385/62640439-e0f9f080-b941-11e9-85ca-8c699ed6df40.jpg)
Hi,
The source is any directory on an HDD (NTFS) the target is any HDD (NTFS) or USB device (NTFS). 
The operating system is Windows 7 Ultimate 64bits (german).

I tried it now on a second PC with Windows 7 Ultimate 64bit (german). The problem is the same.

With Ultracopier 1.6.1.5 the problems don't exists.

Greetings
WusWus

**Comment by alphaonex86** [comment]
I will check what is the problem. Do you have the problem on same drive and same partition?
With Ultracopier 1, Qt manipulate the file, with 2 is API win32.
Same after reboot?

**Comment by WusWus** [comment]
Hello,
Thanks for the quick answer.
The problem is always there. No matter if I copy or move to the same partition, the same drive, from partition to partition, from drive to drive, or between NTFS or FAT32. I have tried everything I could think of and was possible.
I restarted, but there's no change. The problem is always there.
I uninstall Ultracopier, clean the registry from Ultracopier, reboot, reinstall; but no change.

The folder name I'm trying to copy/move is called:
'Überprüfung'

I send the debug report as a PDF file, because no HTML can be uploaded.
[ultracopier-bug-report.log.pdf](https://github.com/alphaonex86/Ultracopier/files/3481541/ultracopier-bug-report.log.pdf)


greetings
WusWus

**Comment by alphaonex86** [comment]
C:\Überprüfung exists? I:\Überprüfung was created?
I search reproduce it, but failed. Can you send me debug report when source and destination are on C:\ ?

**Comment by WusWus** [comment]
OK, here are two debug reports: 

Copy folder 'Überprüfung' from C:\ to C:\ 
[01_ultracopier-bug-report.log.pdf](https://github.com/alphaonex86/Ultracopier/files/3482490/01_ultracopier-bug-report.log.pdf)

Copy folder 'Überprüfung' from C:\ to subfolder C:\-TEMP-\ 
[02_ultracopier-bug-report.log.pdf](https://github.com/alphaonex86/Ultracopier/files/3482491/02_ultracopier-bug-report.log.pdf)

I hope that's helpful.

**Comment by alphaonex86** [comment]
Fixed into 2.0.3.5, compilation in progress, publication today
