### ISSUE TITLE
[UC] Copy stops during operation

### ISSUE THREAD

**Issue by WusWus** [alphaonex86/Ultracopier#35]
Hi, 
Unfortunately, there is another problem. 
The copy stops and some files in some folders will not be copied. 

The folder 'c:\Ultracopier' has been copied to 'C:\\-TEMP\Ultracopier'

I deleted the copied folder and copied it again. This time there are other files that could not be copied. Sometimes it takes a some time until copying starts. 

Dedug report first try: 
[ultracopier-bug-report.log.html.txt](https://github.com/alphaonex86/Ultracopier/files/3487214/ultracopier-bug-report.log.html.txt)
(please delete the .txt extension, it's a html-file  - also the other uploads)

Debug report second try: 
[ultracopier-bug-report.log.html.txt](https://github.com/alphaonex86/Ultracopier/files/3487224/ultracopier-bug-report.log.html.txt)

Ultracopier has been restarted. 

I copied the folder again, Ultracopier stopped again. 
Now I did not delete the copied folder, but copied it again (merge). Now everything has been copied without any problems. I've tried that several times. It can happen that Ultracopier hesitates and then continues; very rarely Ultracopier freezes, and the process has to be killed. 

Debug report first try: 
[ultracopier-bug-report.log.html.txt](https://github.com/alphaonex86/Ultracopier/files/3487230/ultracopier-bug-report.log.html.txt)

Debug report second try: 
[ultracopier-bug-report.log.html.txt](https://github.com/alphaonex86/Ultracopier/files/3487231/ultracopier-bug-report.log.html.txt)

Debug report third try: 
[ultracopier-bug-report.log.html.txt](https://github.com/alphaonex86/Ultracopier/files/3487233/ultracopier-bug-report.log.html.txt)

However, most copy operations with different folders work fine. 
The problem only occurs with some folders.

Bewst regards 
WusWus

**Comment by alphaonex86** [comment]
Hi,
In this case the bug report not help.
Can you define what is the minimal case with minimal files to always produce this kind of problem?
Cheers,

**Comment by WusWus** [comment]
I have tested a lot now. Unfortunately it is impossible to test everything extensively.

Here's the result of my tests: 

- 5 Files can always be copied. 
- A maximum of 10-15 files are not copied (ultracopier stops). 
- If 'merge' is used, ultracopier freezes. Sometimes 'merge' works fine without freezing. 
- Folders (empty) are always copied (tested with 64 subfolders). 
- The number of files to copy seems to be a problem. 
- The distribution of files to subfolders is apparently unimportant. 
- Are in a folder Large files are copied more than 5 files. 
     By default my test was done with .txt-files of maximum 75kb. In a test with 18 files between 21 and 
     960MB, 12 of 18 files were copied. 
- If 'Follow the strict Order' is enabled in the 'Copy Engine Options', the copy process works better; 
     however with 'merge' Ultracopier still freezes. 



- Ultracopier does not ask what to do with duplicate files. The existing files are overwritten unasked, even if 'Rename the original destination' is enabled.



Does that help?

WusWus

**Comment by alphaonex86** [comment]
I will check the next week all this, but some not ocur here.

**Comment by alphaonex86** [comment]
Should be fixed
