### ISSUE TITLE
Issue to copy in "system" folders

### ISSUE THREAD

**Issue by KoDaKrom** [alphaonex86/Ultracopier#37]
Hi developper team,

I'm using old Supercopier and now Ultracopier for long years, thank you!

Here is my problem/request:
- by default after installation, when copying files into "system" folders (where normally Win ask confirmation to paste files), Ultracopier doesn't do the job.
==> solution is to disable Ultracopier and use normal copy function of Windows.
(I'm running Win10 64bits, home edition)

Alternative I've tried is to modify propreties of C:\Program Files\Ultracopier\ultracopier.exe, run always as administrator.
==> the problem mentionned above is solved like this.
**BUT**: I'don't know why, with this modification, ultracopier doesn't start anymore with Windows.
==> must be lauched manually (and after the icon in system tray is visible).

Other question :
I bought the  Ultracopier v1 software, does allow me to download and use the v2 ?

**Comment by alphaonex86** [comment]
Mode adminstrator generate lot of bug.
Maybe you can test with option of pluginLoader -> catchcopy-v0002

As written on the site, the major update (1.x -> 2.x) is not free to support the project.
The version 1.x was free update during more than 5 years and have years old.
You can use the version 1 and disable update detection:
http://files.first-world.info/ultracopier/1.6.1.5/ultracopier-windows-x86-1.6.1.5-setup.exe
http://files.first-world.info/ultracopier/1.6.1.5/ultracopier-windows-x86_64-1.6.1.5-setup.exe
