### ISSUE TITLE
How to run in Linux

### ISSUE THREAD

**Issue by arnauldb** [alphaonex86/Ultracopier#38]
Hello,

I did

> find ./ -name '*.ts' -exec lrelease {} \;
> qmake ultracopier.pro

But what's next?

Thank you.

**Comment by alphaonex86** [comment]
make
and execute the binary

**Comment by arnauldb** [comment]
Thank you, it works and I successfully copied stuff.

However, when I did `make` I had a few errors. Is it bad (I am running Linux Mint Sylvia 18.3)?

> In file included from plugins/CopyEngine/Ultracopier-Spec/ScanFileOrFolder.h:19:0,
>                  from plugins/CopyEngine/Ultracopier-Spec/ListThread.h:22,
>                  from plugins/CopyEngine/Ultracopier-Spec/CopyEngine.h:22,
>                  from plugins/CopyEngine/Ultracopier-Spec/CopyEngineFactory.h:19,
>                  from CopyEngineManager.cpp:13:
> plugins/CopyEngine/Ultracopier-Spec/TransferThread.h:69:29: error: field ‘transferId’ has incomplete type ‘std::atomic<long unsigned int>’
>      std::atomic<uint64_t>   transferId;
>                              ^
> In file included from /usr/include/c++/5/bits/shared_ptr_atomic.h:33:0,
>                  from /usr/include/c++/5/memory:83,
>                  from /usr/include/c++/5/regex:46,
>                  from DebugEngine.h:21,
>                  from DebugEngineMacro.h:20,
>                  from Environment.h:11,
>                  from CopyEngineManager.h:17,
>                  from CopyEngineManager.cpp:8:
> /usr/include/c++/5/bits/atomic_base.h:126:12: note: declaration of ‘struct std::atomic<long unsigned int>’
>      struct atomic;
>             ^
> In file included from plugins/CopyEngine/Ultracopier-Spec/ScanFileOrFolder.h:19:0,
>                  from plugins/CopyEngine/Ultracopier-Spec/ListThread.h:22,
>                  from plugins/CopyEngine/Ultracopier-Spec/CopyEngine.h:22,
>                  from plugins/CopyEngine/Ultracopier-Spec/CopyEngineFactory.h:19,
>                  from CopyEngineManager.cpp:13:
> plugins/CopyEngine/Ultracopier-Spec/TransferThread.h:205:31: error: field ‘transfer_stat’ has incomplete type ‘std::atomic<TransferStat>’
>      std::atomic<TransferStat> transfer_stat;
>                                ^
> In file included from /usr/include/c++/5/bits/shared_ptr_atomic.h:33:0,
>                  from /usr/include/c++/5/memory:83,
>                  from /usr/include/c++/5/regex:46,
>                  from DebugEngine.h:21,
>                  from DebugEngineMacro.h:20,
>                  from Environment.h:11,
>                  from CopyEngineManager.h:17,
>                  from CopyEngineManager.cpp:8:
> /usr/include/c++/5/bits/atomic_base.h:126:12: note: declaration of ‘struct std::atomic<TransferStat>’
>      struct atomic;
>             ^
> Makefile:2053: recipe for target 'CopyEngineManager.o' failed
> make: *** [CopyEngineManager.o] Error 1

**Comment by alphaonex86** [comment]
Hi, try with last commit.
What compiler and OS used?
