### ISSUE TITLE
Ultracopier window always top left corner instead of center

### ISSUE THREAD

**Issue by andrewpros** [alphaonex86/Ultracopier#40]
Can we have an option to display the transfer window always at screen center?

Now it is always at top left corner and it is very irritating, it uses Qt so this should very easy to add.

I mean seriously its almost 2020 https://wiki.qt.io/How_to_Center_a_Window_on_the_Screen

**Comment by alphaonex86** [comment]
You can't do this with Options -> Themes -> Save position option?
The problem here it's do the jobs of windows manager because is poor on some OS generate lot of bug, work to maintain, and it's few bit out of scope, I will study it for the version 2.2

**Comment by andrewpros** [comment]
Yes i can and it works, didn't know it was there, but what is the issue if there is already code that sets the window position after saving?

It is already there, so instead of loading position data we could just get the desktop bounds, calculate center and display it there, maybe add another option just like saving position?

I don't know about any issues with centering windows in Qt, it just works fine, there in nothing to study and as an option if it wont work for someone there is always save position, dont need to use any of those options.

Where should i look for the transfer window initialization? If i made a PR with a center window option will u accept it, i dont want to wait til 2.2, it will be long time.

**Comment by alphaonex86** [comment]
Example of problem to manager: dual screen.
I had difficult to understand your English and I don't had understand your last sentence.

**Comment by andrewpros** [comment]
But dual screen users are like 0.1% user base, besides, as and option it would not be forced.

I asked where is the code that shows/creates the transfer window, so i can look at it and maybe create a Pull request? I dont want to wait for 2.2 version, but do u accept pull requests?

**Comment by alphaonex86** [comment]
https://github.com/alphaonex86/Ultracopier/blob/master/plugins/Themes/Oxygen2/ThemesFactory.cpp#L56

**Comment by cglmrfreeman** [comment]
I have the task bar on the top. I was unable to move Ultracopier until I unlocked and moved my taskbar...

**Comment by alphaonex86** [comment]
Hi,
With the default option?

**Comment by cglmrfreeman** [comment]
After a fresh install, yes.

**Comment by alphaonex86** [comment]
Try save the option: save position

**Comment by cglmrfreeman** [comment]
I guess I am failing to see where that's an available option or why that option isn't selected by default.

**Comment by alphaonex86** [comment]
Fixed into version 2.2.6.5
