### ISSUE TITLE
Silent uninstall

### ISSUE THREAD

**Issue by jpele-tis** [alphaonex86/Ultracopier#55]
I am unable to uninstall Ultracopier with my SDT.

`uninst.exe /S` do not work

May you confirm us if it's possible ? Can we plan to add this feature ?

**Comment by alphaonex86** [comment]
I have never test the unisinstaller like this.
Some dll can be locker due to Windows API.
You can just drop folder + registry folder.

**Comment by jpele-tis** [comment]
It's not proper :/ Can you consider this implementation ?
We manage our Software Deployment Tool (SDT) solution, called WAPT, and for now on our store, for now we mention "Uninstall is NOT silent" see here https://store.wapt.fr/store/tis-ultracopier

**Comment by alphaonex86** [comment]
1. nullsoft is very old installer, if not support I can't do it
2. is all case silent install or will failed because some dll is always locked
3. ok

**Comment by jpele-tis** [comment]
@alphaonex86 
It is supported on Nullsoft Scriptable Install System.

Incidentally, all /S does is change the installer script's SilentInstall attribute from "normal" to "silent". What effect this has, exactly, depends on the person who wrote the script. If /S does not perform a silent install, **consider submitting a bug report to the installer's creator**.

Sources:
http://unattended.sourceforge.net/installers.php
http://nsis.sourceforge.net/Docs/Chapter4.html#4.8.1.36
