### ISSUE TITLE
Lost files while trying to move them

### ISSUE THREAD

**Issue by nbros** [alphaonex86/Ultracopier#56]
Hello,
Using Ultracopier 2.2.4.8, I was moving files from an NTFS local disk to an extFAT external disk.
While the files were being moved, I used shift+drag to move more files to the Ultracopier window.
Ultracopier asked if I wanted to move the files to the same folder and I clicked Yes.
Ultracopier started complaining for each file that it couldn't find it in the source folder.
All these files were created with a size of 0 bytes in the destination and were deleted and unrecoverable in the source.

**Comment by alphaonex86** [comment]
Hi, thanks for the repport, I will check this today.

**Comment by alphaonex86** [comment]
Can you reproduce that's? How?

**Comment by nbros** [comment]
The download site seems to be down: "502 Bad Gateway" so I could not get the debug version.

But yes, the problem is reproducible:

![ultracopier_file_loss](https://user-images.githubusercontent.com/141089/102499355-59ff7100-407b-11eb-8f61-f528f6c0ace8.gif)

**Comment by alphaonex86** [comment]
Download fixed, for now, I try reproduce here, but no problem here (from an NTFS local disk to an extFAT external disk too)

**Comment by alphaonex86** [comment]
Hi, When Ultracopier accept in this mode, Windows just send the file to trash... I will disable this for move. You can add more file to move via the menu

**Comment by nbros** [comment]
Hello,
Thank you for the fix!
The link for the new version seems broken though:
https://cdn.confiared.com/files.first-world.info/ultracopier/2.2.4.9/ultracopier-windows-x86_64-2.2.4.9-setup.exe
`Error: Add client to dead http url downloader`

**Comment by alphaonex86** [comment]
Hi, I had use my time to debug this bug, and I need more time to fix the CDN.
I'm working on this
