### ISSUE TITLE
No public builds available. Only easily accessible bulds contains ads.

### ISSUE THREAD

**Issue by wowitsjack** [alphaonex86/Ultracopier#59]
Hi!

I notice there are no builds of the project made available here on the open source project page.

All copies of the old ad-free SuperCoper on the author's site have been hijacked to point to the upsell-version of paid Ultracopier.

For a project that was running hidden crypto miners on users computers without permission, this seems like a very suspicious move.

Can we please have some clean, verifiable releases here on Github, and some instructions for an easy at-home build?

**Comment by alphaonex86** [comment]
Hi,
The project don't run any crypto miner.
Release here is hard, and time consuming. The ad line is very little on interface.
you can just compile with Qt the ultracopier.pro of the project.
