### ISSUE TITLE
Is Ultracopier compatible with server-side copy offload ?

### ISSUE THREAD

**Issue by sviscapi** [alphaonex86/Ultracopier#62]
Dear @alphaonex86 ,

Is Ultracopier compatible with server-side copy offload ?

https://superuser.com/questions/1361215/how-to-efficiently-transfer-large-files-between-two-remote-locations-on-same-ser

A colleague of mine tried recently to copy a 71GB archive on a remote Windows 2012 server from \\remote_server\directory1 to \\remote_server\directory2. When using Ultracopier on her Windows 10 client, the copy time was estimated to **4 hours**. When using the stock copy / paste function of the OS, the copy was completed in **11 minutes**.

Could you please shed some light on this issue ?

Best regards,

Samuel

**Comment by alphaonex86** [comment]
Hi,
The copy data stream pass by Ultracopier to limit the copy speed. But if you need the maximum stream you can try the OS native copy option, this call the native copy by file in internal.
Say me if it help please.
Cheers,

**Comment by alphaonex86** [comment]
![image](https://user-images.githubusercontent.com/778581/159469981-0e28eb1a-36ef-4650-879b-58e906dd78b8.png)
Os native copy

**Comment by sviscapi** [comment]
Dear @alphaonex86 ,

It works like a charm, thank you very much :)

Details about the duration of the transfer seem to be missing when using the OS native copy.

Is it a bug or a missing feature ?

Best regards,

Samuel

**Comment by alphaonex86** [comment]
Bug, I will investigate about this.
