### ISSUE TITLE
Please add merge/overwrite option "Overwrite only if source is bigger"

### ISSUE THREAD

**Issue by shodanx2** [alphaonex86/Ultracopier#68]
Hi,

Imagine the following case, you are overwriting/merge a massive 1 teraby folder, the two folders are nearly identical but some files are missing from the source in the destination. You could imagine that these are two copies of the same folder but one got damaged perhaps, or it has become unclear which has all the files.

So you just set to overwrite the entire folder using the merge function

These are the current option

![image](https://user-images.githubusercontent.com/10621885/188296374-a021a4f8-03b1-4427-933a-3a2341a2f1ba.png)

You could overwrite only the newer files, but if you have copied the source folder over the network, all the file dates will be newer.

So that really only leaves "if not same size" but imagine the following horror scenario.

Some files in the source folders are broken, they have become empty, 0 byte files.   "if not same size" the empty files will overwrite the real, good files, oh no !

This is where "Overwrite only if source is bigger"  comes in. Now you can confidently overwrite the entire folder and it's unlikely that bigger file is corrupt or older !

****   Supplement ****

This would already be great, however for even more functionality there could be the following option.

When overwriting a file in the destination from the source, the file in the destination could be moved to an overflow folder.

Just in case.

So you choose an option maybe "overwrite if XYZ but keep overwriting file in overflow"  

The overflow folder could be in the user's temp folder (%TMP  C:\Users\username\AppData\Local\Temp)
And it would be kept in the same relative path

So imagine I have copying 

from D:\games\steam\steamapps\common\

to E:\test\

and the file D:\games\steam\steamapps\common\3DMark 11\bin\x86\dxinfo.exe to E:\test\3DMark 11\bin\x86\dxinfo.exe 

is about to be overwritten, the source will be copied over, but the already existing file E:\test\3DMark 11\bin\x86\dxinfo.exe  would be dumped in %TMP%\3DMark 11\bin\x86\dxinfo.exe

**Comment by alphaonex86** [comment]
Hi, I validate the idea for the version 3.
Supplement: no for the reason:

- Special folder generate problem
- The newbies user will just see ultracopier stolen their free space and don't understand why
- what do in case of collision?
- add more complexity, then bug and difficult to maintain the software. it's not just add a features, the most important is keep the data integrity
