### ISSUE TITLE
Not working with windows 11

### ISSUE THREAD

**Issue by boistordu** [alphaonex86/Ultracopier#72]
What ever I tried, even doing a custom task in the task scheduler with the highest admin privileges and the admin group does not replace the windows transfer file system. 
But ultracopier is booting accordingly.

**Comment by boistordu** [comment]
It does work under another normal user and copy system is correctly replaced. 
But the software is not registered so I had to launch it manually. 

So the problem of the replacement of the os default copying system is contained to the admin local account

**Comment by alphaonex86** [comment]
yes, ultracopier is limited to the current account due to windows policy, it crash when try communicate in cross account.
