### ISSUE TITLE
Autostart not work

### ISSUE THREAD

**Issue by KobeLAL** [alphaonex86/Ultracopier#78]
Hello,

I am using Ultracopier under Windows 11. This also works (is displayed in the tray). After a restart, the programme is not started automatically (set in the settings). I always have to start it myself.

**Comment by alphaonex86** [comment]
Check if the key was created into Software\\Microsoft\\Windows\\CurrentVersion\\Run into the registry (regedit.exe)

**Comment by KobeLAL** [comment]
Yes, the entry is there. I have found the problem. I have set Run programme as administrator in Ultracopier (right click on the shortcut). That's why the autostart didn't work. I think I had a copying problem that I could only fix by starting Ultracopier as administrator.

**Comment by alphaonex86** [comment]
Hi,
Run as administrator generate lot of kind problem, like explorer.exe can't send the copy via named pipe to ultracopier.exe
Then it's blocked to prevent wrong bug report.
