### ISSUE TITLE
Unable to copy/move/transfer files and directories containing curly brackets on name using drag&drop

### ISSUE THREAD

**Issue by LightDestory** [alphaonex86/Ultracopier#79]
As the title says, UC fails to operate with files and directories that contains curly brackets on their name.

It seems that UC uses a URL encoding for the name and such thing breaks the paths.

**Comment by alphaonex86** [comment]
Hi, can you generate a debug report with the debug version:
https://ultracopier.herman-brule.com/files/2.2.6.5/ultracopier-debug-windows-x86-2.2.6.5.zip

1. do the bug
2. right click on system tray icon (near the clock)
3. save the debug report
4. Attach it here

**Comment by LightDestory** [comment]
Unfortunately it is not a windows environment. It is Fedora

**Comment by alphaonex86** [comment]
Remember me the next week, Linux is too my main OS, then I can check on Linux

**Comment by LightDestory** [comment]
It seems that also file with the ` character are bugged

**Comment by alphaonex86** [comment]
In my case I can perfectly copy it, Ultracopier 2.2.6.4, from and to /home ext4 partion

**Comment by LightDestory** [comment]
> In my case I can perfectly copy it, Ultracopier 2.2.6.4, from and to /home ext4 partion

In my case doesn't work: copying from ext4 partition to a NFS partition. The issue is only with files containing curly brackets or ` on their filename. Everything else work like excepted.

**Comment by alphaonex86** [comment]
Can you test from ext4 and to ext4?
Can you details the version and method to copy a file?

**Comment by LightDestory** [comment]
I tried to uninstall the distro provided package and compile from source. It is still not working.

I tried a copy from ext4 to ext4 but I got the same issue, a 0byte file is created but nothing more.

**Comment by alphaonex86** [comment]
Method I use:

- Right click on the system tray
- Add copy
- Esc key (or cancel)
- More
-  Add
- Add file

**Comment by LightDestory** [comment]
Oh my god, with "add file" it works!

It seems that drag & drop is bugged

**Comment by alphaonex86** [comment]
Fixed into the new published version 2.2.6.6
