### ISSUE TITLE
Copy form NTFS to exfat have a diference in modify time (with keep date)

### ISSUE THREAD

**Issue by fraynaud33** [alphaonex86/Ultracopier#80]
Hello,
I found when I copy files from my hard drive ntfs to my external drive in exfat, modify time is not the same in 2s.
So when I recopy the same file, if I choose erase when size or date is different, it was rewriting.
Here the example. The origine file was downloaded on D:\download (modify time 21:28:28). Copy with ultracopier to J:\ the internal drive in ntfs (21:28:28) and to K:\ the external drive in exfat (21:28:30).
![image](https://user-images.githubusercontent.com/26875828/214144793-c8a383cf-91d5-4c56-8f3e-2cbf42d3f7ad.png)
I will try with an external drive in ntfs and it works, the modify date was the same (21:28:28).

**Comment by alphaonex86** [comment]
Function I use to read time:
https://github.com/alphaonex86/Ultracopier/blob/master/plugins/CopyEngine/Ultracopier-Spec/TransferThread.cpp#L1014
Function I use to write time:
https://github.com/alphaonex86/Ultracopier/blob/master/plugins/CopyEngine/Ultracopier-Spec/TransferThread.cpp#L1080
Then I seam do it correctly, it's specific bug to windows

**Comment by fraynaud33** [comment]
Thank you for your answer.
I have another question before closing this ticket : @alphaonex86 
Is it possible to keep date to folder too ?
Even in NTFS, the creation date of a folder I copy is the now time and not the creation time of the folder.

**Comment by alphaonex86** [comment]
If you need keep folder date, put this 2 options:

- keep date
- inode thread = 1

**Comment by fraynaud33** [comment]
Sorry to be late to answer. I don't find "keep date" but "keep the file date". And with inode Thread = 1 when I Copy on windows 10 a folder from an inernal hard drive in ntfs to another hard drive in ntfs It doesn't keep folder date.
Maybe it's windows who doesn't allowed this ?

**Comment by alphaonex86** [comment]
keep the file date try too apply to folder. I think in you case it's not possible
