### ISSUE TITLE
"Always perform this action" for "put at the bottom" for "wrong modification date" does not work

### ISSUE THREAD

**Issue by Loda** [alphaonex86/Ultracopier#82]
I have UC 2.2.4.7. on Ubuntu 22 wayland. I installed it with apt-get install and lunch it from the terminal.
I copy from external usb NTFS to external usb NTFS
when copying some old file (56B .ico), the modification date cannot be read. and the prompt popup.

the option "Always perform this action" for "put at the bottom" does not work, as UC will prompt again on the next file in the same folder.

suggestion: add an option for "keep the file date" -> "keep the file date if possible (silently ignore modification date error)".

this kind of issue is especially problematic as I use UC to make 500GB+ copies of a lot of small files.

**Comment by alphaonex86** [comment]
Hi, already fixed into the last version (uncheck keep date, will try and silently ignore if failed), request ubuntu update the packages
