### ISSUE TITLE
Copy stops at 1,67TB

### ISSUE THREAD

**Issue by Axellarator** [alphaonex86/Ultracopier#84]
Trying to copy from different folders roughly 6 TB data. The process stops always at 1.67TB

**Comment by alphaonex86** [comment]
Hi, have you more data? WindowsI have copied 200TB of data without problem

**Comment by Axellarator** [comment]
Windows 11 is the OS. UC is much faster than FastCopy average of 270 MB/s compared to 50 MB/s. I tried the full HDD first. It stopped at 1.67 TB than I tried the Steam directory alone. It stops at 1.67 TB. And I got no errors. Which kind of information do you need?

**Comment by alphaonex86** [comment]
https://cdn.confiared.com/ultracopier.herman-brule.com/files/2.2.6.6/ultracopier-debug-windows-x86-2.2.6.6.zip
You should with this version see 2 windows during the copy, then I will need:
![image](https://github.com/alphaonex86/Ultracopier/assets/778581/d41e0b12-c361-45c3-b454-ce9eb35df7b4)
When stop the copy

**Comment by Axellarator** [comment]
I started UC with admin rights. Now I get "Not enough memory on target drive. Target drive has 8 of 15 TB space.

**Comment by alphaonex86** [comment]
UC is not designed to run as admin, just run as normal user.

**Comment by Axellarator** [comment]
I tried it again, it works now with 450 GB in admin mode. But I found that at the same time a Windows update happened and a Windows Defender search. Now a reboot is requested. 
Number of inode is 16, rest is zero

**Comment by alphaonex86** [comment]
I need the informations into this windows when it not work

**Comment by Axellarator** [comment]
I think I got it. It is the USB Drive. The OS stops the drive and either kicks out the copy program and asks what shall it do with the new drive. Message one is: can't find the path or two: Device not found. 

It is the USB drive, It stops working and the OS recognized it as a new connection. And the copy process stops or get a hickup.

**Comment by alphaonex86** [comment]
Hi, then I have no way to fix in my side, I let's you fix your OS/USB

**Comment by Axellarator** [comment]
Yes true, nevertheless Thanks for your time and help!

**Comment by Axellarator** [comment]
Sure, But later. I am occupied
Axel

Am 2. Juni 2023 17:48:10 MESZ schrieb BRULE Herman Jacques Roger ***@***.***>:
