### ISSUE TITLE
Cannot compile under Ubuntu 22.04.3

### ISSUE THREAD

**Issue by StefanPofahl** [alphaonex86/Ultracopier#87]
I followed the instruction given in this repository:
```bash
sudo apt install make gcc qtmultimedia5-dev libogg-dev libopus-dev libgl1-mesa-dev
```
I moved into the directory of the source code of Ultracopier and than executed the following commands:
```bash
find ./ -name '*.ts' -exec lrelease {} \;
qmake ultracopier.pro
make -j$(nproc)
```
And here are the error messages:
```unicode
In file included from libopus/silk/SigProc_FIX.h:40,
                 from libopus/silk/inner_prod_aligned.c:32:
/usr/include/string.h:26:10: fatal error: bits/libc-header-start.h: No such file or directory
   26 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from opusfile/internal.h:31,
                 from opusfile/opusfile.c:21:
/usr/include/stdlib.h:26:10: fatal error: bits/libc-header-start.h: No such file or directory
   26 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from libogg/bitwise.c:21:
/usr/include/string.h:26:10: fatal error: bits/libc-header-start.h: No such file or directory
   26 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from libopus/silk/SigProc_FIX.h:40,
                 from libopus/silk/ana_filt_bank_1.c:32:
/usr/include/string.h:26:10: fatal error: bits/libc-header-start.h: No such file or directory
   26 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from libogg/framing.c:23:
/usr/include/stdlib.h:26:10: fatal error: bits/libc-header-start.h: No such file or directory
   26 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from opusfile/internal.h:31,
                 from opusfile/stream.c:21:
/usr/include/stdlib.h:26:10: fatal error: bits/libc-header-start.h: No such file or directory
   26 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from opusfile/internal.h:31,
                 from opusfile/info.c:16:
/usr/include/stdlib.h:26:10: fatal error: bits/libc-header-start.h: No such file or directory
   26 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
compilation terminated.
compilation terminated.
In file included from opusfile/internal.h:31,
                 from opusfile/internal.c:16:
/usr/include/stdlib.h:26:10: fatal error: bits/libc-header-start.h: No such file or directory
   26 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:10134: ana_filt_bank_1.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:10007: framing.o] Error 1
make: *** [Makefile:10046: internal.o] Error 1
make: *** [Makefile:10090: stream.o] Error 1
make: *** [Makefile:9992: bitwise.o] Error 1
make: *** [Makefile:10178: inner_prod_aligned.o] Error 1
make: *** [Makefile:10028: info.o] Error 1
make: *** [Makefile:10069: opusfile.o] Error 1
```

I hope this clarifies the situation.

**Comment by StefanPofahl** [comment]
Thanks for the immediate response and suggestion!!! :-)
The answer of the command above is:
```monospace
[...]
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.
```
All dependencies are already there ...

**Comment by StefanPofahl** [comment]
This time a lot of stuff had been installed:
```monospace
0 upgraded, 23 newly installed, 0 to remove and 16 not upgraded.
Need to get 19,0 MB of archives.
After this operation, 70,3 MB of additional disk space will be used.
```
And the compilation was completed without error  messages :-) 
Thanks for the support!

**Comment by StefanPofahl** [comment]
Compilation seemed to be successful, but no User-Interface can be seen ...

**Comment by alphaonex86** [comment]
Hi, you should have icon into the system tray near the clock

**Comment by StefanPofahl** [comment]
Unfortunately no icon.
./ultracopier
fails
![no_icon_ultracopier](https://github.com/alphaonex86/Ultracopier/assets/65159315/f374e3ce-ae86-4fac-ac25-72548744fcb1)

**Comment by alphaonex86** [comment]
and into inactive icon (arrow up)?
I use too KDE, and have the icon

**Comment by StefanPofahl** [comment]
unfortunately not:
![no_icon_ultracopier_arrow_up](https://github.com/alphaonex86/Ultracopier/assets/65159315/f6f89b86-e9ad-415a-b72f-a9785e8d11ff)

**Comment by alphaonex86** [comment]
wayland? I will try with this version.
Strange, I use the standard Qt system tray icon.
other-pro/ultracopier-little.pro is window only version, is well for one time use

**Comment by alphaonex86** [comment]
![image](https://github.com/alphaonex86/Ultracopier/assets/778581/b079ca22-070b-498d-b750-b709bb7a71b9)
![image](https://github.com/alphaonex86/Ultracopier/assets/778581/07c12f00-7d40-4c29-ae5a-55c0daef4962)
With ubuntu 22.04.3 default and ubuntu 22.04.3 with kde-full

**Comment by StefanPofahl** [comment]
I had issues with display plots in `julia`, the famous Gtk issue:
```
Gtk-Message: 08:02:22.631: Failed to load module "what-so-ever"
```
One advice was to install `wayland` via:
```
sudo apt-get -y install qt6-wayland
```
Maybe this was a bad idea?

Maybe a stupid question, how do I install your package in the end?
Currently the executable `ultracopier` is located here:
```
~/Downloads/Ultracopier-master/ultracopier
```
Is this meaningful? - What is the next step after the compilation of your package?

**Comment by alphaonex86** [comment]
I think your problem is into your Linux, it's broken, you have to search how fix it.
wayland is not needed, and by default ultracopier compile as qt5, no qt6
you can: mv ~/Downloads/Ultracopier-master/ultracopier /usr/local/bin to integrate into your system

**Comment by StefanPofahl** [comment]
thanks for clarification!
in other words: if I manage to get back to qt5, your software should start on my kubuntu 22.04.3?

If this is the case, it might be usefull to check the version of `Qt` either during compilation or during start up to inform the user that there is a version missmatch of `Qt`. What do you think?
Are there plans to make your software `qt6` compatible?
Ok, if I read carefully your `readme.md` it lists `qtmultimedia5-dev` as dependency, but for me, who is just looking for a suitable copy-SW, the connex between this dependency and the incompatibility to my system was not obvious.

**Comment by alphaonex86** [comment]
ultracopier work well with qt6, with need be only qt5 or only qt6

**Comment by StefanPofahl** [comment]
What about the package: `qt5-style-plugins`? - Should it be installed as well?
On my system this package was missing. 
See:
https://askubuntu.com/questions/1398554/unable-to-change-qt-qpa-platformtheme-environment-variable
https://askubuntu.com/questions/910012/how-can-i-get-qt5-applications-to-use-the-gtk-theme-in-ubuntu-17-04/952571#952571

**Comment by alphaonex86** [comment]
you can test

**Comment by StefanPofahl** [comment]
I did already, it is not harmful. - But I wonder, if it is relevant.
