### ISSUE TITLE
Unable to move the folder

### ISSUE THREAD

**Issue by TiTi** [alphaonex86/Ultracopier#9]
When cut (ctrl+x) / paste (ctrl+v) a folder, I sometimes got:

> Unable to move the folder
- When it happen, the issue is reproduceable each time. I have no other way than to quit UltraCopier.
- Copy/Paste works fine
- If I copy the folder, then cut/paste the copied folder, it works (wow)
- Permissions seem ok
- Using Windows 64bits version
- I've tried to write the log file but nothing is written (no errors)
- Cut/Paste works fine with windows explorer

**Comment by alphaonex86** [comment]
http://files.first-world.info/ultracopier/1.2.0.2/ultracopier-debug-windows-x86-1.2.0.2.zip -> give more informations?
Have you a way to reproduct that's?

**Comment by TiTi** [comment]
Dammit, I couldn't reproduce it tonight with the folder I had an issue
with...

But this happen from time to time.

Yesterday I was moving this folder to another location which is monitored
by a cloud sync. application.
I don't think it's related because I had similar issues before this,
outside of the monitored folder.
But they do some shadow copy stuff which might not help in some cases.
Others folders were ok but not this one.

I'll definitively test with your debug build in case it happen again.

By the way: es-tu français ?

**Comment by alphaonex86** [comment]
Oui je suis francais

**Comment by TiTi** [comment]
Ok là j'en ai un. J'obtiens : 

>  Access is denied

Erf pas la même erreur.
Ce sont des fichiers sur un HDD externe.
Bon les permissions comportent des "Account Unknown" mais y'a le group SYSTEM qui a droit en Read et Write.
Et je suis à peu près certain que ca va marcher avec la copie windows.
Mais je ne le fais pas pour troubleshooter.

Je viens d'essayer avec http://files.first-world.info/ultracopier/1.2.0.4/ultracopier-debug-windows-x86-1.2.0.4.zip

```
(   22005) ListThread.cpp:1836:newTransferStat(), (location: Copy Engine plugin): TransferStat: 3
(   22005) ReadThread.cpp:474:startRead(), (location: Copy Engine plugin): [0] start
(   22005) ReadThread.cpp:364:internalRead(), (location: Copy Engine plugin): [0] start the copy
(   22005) TransferThread.cpp:1554:readIsStopped(), (location: Copy Engine plugin): [0] emit readIsStopped()
(   22005) ListThread.cpp:1632:doNewActions_start_transfer(), (location: Copy Engine plugin): actionToDoListTransfer.size(): 14, numberOfTranferRuning
: 0
(   22005) ListThread.cpp:1674:doNewActions_start_transfer(), (location: Copy Engine plugin): numberOfTranferRuning: 0
(   22005) TransferThread.cpp:1017:readIsFinish(), (location: Copy Engine plugin): [0] start
(   22005) ListThread.cpp:1836:newTransferStat(), (location: Copy Engine plugin): TransferStat: 5
(   22005) ReadThread.cpp:469:internalRead(), (location: Copy Engine plugin): [0] stop the read
(   22005) WriteThread.cpp:944:internalWrite(), (location: Copy Engine plugin): [0] emit writeIsStarted()
(   22006) WriteThread.cpp:314:endIsDetected(), (location: Copy Engine plugin): [0] start
(   22006) TransferThread.cpp:1113:readIsClosed(), (location: Copy Engine plugin): [0] start
(   22006) TransferThread.cpp:1162:checkIfAllIsClosedAndDoOperations(), (location: Copy Engine plugin): [0] wait self close: readIsReadyVariable: 1, r
eadIsClosedVariable: 1, writeIsReadyVariable: 1, writeIsClosedVariable: 0
(   22006) WriteThread.cpp:381:internalEndOfFile(), (location: Copy Engine plugin): [0] writeIsStopped
(   22006) TransferThread.cpp:1567:writeIsStopped(), (location: Copy Engine plugin): [0] start
(   22006) TransferThread.cpp:1570:writeIsStopped(), (location: Copy Engine plugin): [0] emit writeStopped()
(   22006) TransferThread.cpp:1048:writeIsFinish(), (location: Copy Engine plugin): [0] start
(   22006) WriteThread.cpp:471:postOperation(), (location: Copy Engine plugin): [0] start
(   22006) WriteThread.cpp:482:internalClose(), (location: Copy Engine plugin): [0] close for file: W:/TV Shows/Harpers Island/folder.jpg
(   22006) TransferThread.cpp:1126:writeIsClosed(), (location: Copy Engine plugin): [0] start
(   22006) TransferThread.cpp:1149:checkIfAllIsClosedAndDoOperations(), (location: Copy Engine plugin): [0] emit internalStartPostOperation() to do th
e real post operation
(   22006) TransferThread.cpp:1176:postOperation(), (location: Copy Engine plugin): [0] start
(   22007) TransferThread.cpp:1714:writeFileDateTime(), (location: Copy Engine plugin): [0] writeFileDateTime(W:/TV Shows/Harpers Island/folder.jpg)
(   22007) CopyEngine-collision-and-error.cpp:247:errorOnFile(), (location: Copy Engine plugin): file have error: X:/TV Shows/Harpers Island/folder.jp
g, error: Access is denied.

(   22007) CopyEngine-collision-and-error.cpp:281:errorOnFile(), (location: Copy Engine plugin): show dialog
```

Est-ce que tu veux le rapport complet ?

**Comment by alphaonex86** [comment]
Sauf que ultracopier respecte les droits et ne les contournes pas comme le copier/coller de windows.
N'importe quel application Qt aurai aussi des problémes de droits, et peu être les autres application tiré de unix (firefox/chrome).

**Comment by TiTi** [comment]
Ok. Du coup j'ai rajouté mon user avec les droits Full Control. Et ça marche bien là.
Je vais surveiller si j'obtiens de nouveau l'erreur : Unable to move the folder

Mais y'a des choses que ça soit du même genre, avec copie de tous les fichiers mais suppression du dossier impossible ou dans le style.
