### ISSUE TITLE
Can't copy a directory with non-latin characters properly

### ISSUE THREAD

**Issue by utuhiro78** [alphaonex86/Ultracopier#93]
Ultracopier can't copy a directory with non-latin characters properly.

```
mkdir tmp_ultracopier
cd tmp_ultracopier/

# Install a CJK font to show Japanese characters.
wget -N https://github.com/googlefonts/noto-cjk/raw/main/Sans/OTC/NotoSansCJK-Regular.ttc
mkdir -p ~/.local/share/fonts/
cp -f NotoSansCJK-Regular.ttc ~/.local/share/fonts/

# Make a directory with non-latin characters.
wget https://github.com/alphaonex86/Ultracopier/archive/refs/heads/master.zip
unzip master.zip
mv Ultracopier-master/ テスト
```

Copy the directory "テスト" to $HOME by ultracopier.
It generates broken directories.

```
cd
ls -d テ*

テ <= Broken
'テス'$'\343' <= Broken
'テス'$'\343\203'<= Broken
テスト <= OK
```

**Comment by alphaonex86** [comment]
I confirm it, it's not a simple bug, the POSIX standard is respected, I will investigate it the next week

**Comment by alphaonex86** [comment]
Can you download and rebuild whole the version from git?

**Comment by utuhiro78** [comment]
> I will investigate it the next week

Thanks!

> Can you download and rebuild whole the version from git?

Yes. I'm using ultracopier-git on Arch Linux.

**Comment by alphaonex86** [comment]
With the last commit all should be fixed
https://github.com/alphaonex86/Ultracopier/commit/877de47db3913a692821b30aa130c09653f895a6

**Comment by utuhiro78** [comment]
I tested it and it works properly.
Thank you so much!
