### ISSUE TITLE
Can't change the language by "Force the language" on Linux

### ISSUE THREAD

**Issue by utuhiro78** [alphaonex86/Ultracopier#94]
"Force the language" only shows English, so I can't change the language.
I'm using ultracopier-git on Arch Linux.

```
wget https://github.com/alphaonex86/Ultracopier/archive/refs/heads/master.zip
unzip master.zip
cd Ultracopier-master/
find ./ -name '*.ts' -exec lrelease {} \;
qmake ultracopier.pro
make -j$(nproc)
./ultracopier
```

Options => General => Check "Force the language" => Change the language

![ultracopier_force_the_language](https://github.com/alphaonex86/Ultracopier/assets/34818411/dffc4aca-d026-4ce0-aabe-1c28b8c653b1)

Do I need to install translation files to somewhere?

**Comment by alphaonex86** [comment]
Hi, yes or into general system or into the personal folder, into plugin format (same as found into the source)

**Comment by utuhiro78** [comment]
`make install` doesn't do anything.

```
make: Nothing to be done for 'install'.
```

I checked ultracopier files in Debian sid.
https://packages.debian.org/ja/sid/amd64/ultracopier/filelist

It doesn't have language files and I don't know where to install them.

Ultracopier is easy to use, so I give up translation.

Thanks.

**Comment by alphaonex86** [comment]
Hi,
Where it search plugin for:
user space folder:

- /home/user/.config/Ultracopier/Languages/

System folder:

- /usr/share/ultracopier/
- /usr/lib/ultracopier/

for the fr Language plugin:
ls -1 /home/user/.config/Ultracopier/Languages/fr/

- flag.png
- informations.xml
- translation.qm
