### ISSUE TITLE
where to ship built plugins,themes in installation package?

### ISSUE THREAD

**Issue by ahmedmoselhi** [alphaonex86/Ultracopier#99]
Hi I've built supercopier package for opensuse tumbleweed in obs using this spec file [here](https://build.opensuse.org/package/view_file/home:ahmedmoselhi2/ultracopier/ultracopier.spec?expand=1) and everything were built finre but now I can't determine which path and what files are needed for each of my built theme-plugin nad there is no documentation available for this

**Comment by alphaonex86** [comment]
Will search plugin into folder: Copy engine,Languages,Listener,Plugin loader,Session loader,Themes into:
~/.config/Ultracopier/
/usr/share/ultracopier/
/usr/lib/ultracopier/
Each language plugin folder contain: flag.png  informations.xml  translation.qm  translation.ts
Each plugin folder contain: informations.xml lib*.so, eg libcopyEngine.so for copyEngine plugin

**Comment by ahmedmoselhi** [comment]
how to start debug mode?

**Comment by alphaonex86** [comment]
Eanble #define ULTRACOPIER_DEBUG into Variable.h

**Comment by ahmedmoselhi** [comment]
I tried build using qt5-creator  and obtained this bug report :
[ultracopier-bug-report.zip](https://github.com/alphaonex86/Ultracopier/files/13515052/ultracopier-bug-report.zip)

**Comment by alphaonex86** [comment]
Version as all in one, direct -> you need compile the version core
other-pro/ultracopier-core.pro

**Comment by ahmedmoselhi** [comment]
fixed now thanks for help

**Comment by ahmedmoselhi** [comment]
solved. btw what is the difference between ultracopier-spec , rsync and random copy engines?

**Comment by alphaonex86** [comment]
rsync delete the destination when not exist into source, it's risky but usefull for backup.

random show random data and do nothing, it's for demo
